Development
JKetelaar/Dockit pull request #1
Opened 2018-06-13 16:39 UTC by JKetelaar

2018-06-15 07:16 UTC, EdinTC requested changes

2018-06-15 07:16 UTC, EdinTC commented on src/JKetelaar/Dockit/Common/CommandLine.php
> + * @author JKetelaar
You forgot this in cli/dockit.php 😄

2018-06-15 07:16 UTC, EdinTC commented on resources/docker/dockit/docker-compose.yml.twig
> +            - "/Users/jeroen/.dockit/data/mysql:/var/lib/mysql"
"/Users/jeroen/.." ?

2018-06-15 09:01 UTC, JKetelaar commented on resources/docker/dockit/docker-compose.yml.twig
> +            - "/Users/jeroen/.dockit/data/mysql:/var/lib/mysql"
Wow good catch 👏

2018-06-20 11:19 UTC, EdinTC commented on README.md
> +brew install php@7.2
It could be a nice feature to give the user a choice on what PHP version they would like to use?

2018-06-20 11:19 UTC, EdinTC commented on resources/docker/docker/php-fpm/php-ini-overrides.ini.twig
> +xdebug.idekey=PHPSTORM
What if someone doesn't use PHPStorm?

2018-06-20 11:19 UTC, EdinTC commented on resources/docker/dockit/nginx.conf.twig
> +    gzip_types *;
I do not think this is a good idea, what if this starts compressing binary files or images?

2018-06-20 11:22 UTC, JKetelaar commented on README.md
> +brew install php@7.2
Correct, but to use this tool you need php >= 7.2 locally. For the Dockit environments, you can select any PHP version.

2018-06-20 11:22 UTC, JKetelaar commented on resources/docker/docker/php-fpm/php-ini-overrides.ini.twig
> +xdebug.idekey=PHPSTORM
Fair enough

2018-06-26 08:12 UTC, EdinTC commented on README.md
> +brew install php@7.2
The comment above is out of date then (>= 7.1)

2018-06-26 08:21 UTC, EdinTC commented on composer.json
> +        "php": ">=7.1.0",
Isn't this supposed to be 7.2?

2018-06-26 08:21 UTC, EdinTC commented on resources/docker/dockit/nginx.conf.twig
> +    port_in_redirect    off;
Extra spaces

2018-06-26 08:21 UTC, EdinTC commented on src/JKetelaar/Dockit/Docker/Config.php
> +                'Please select the PHP version (default "7.1")',
Missing 7.2?

2018-07-23 08:50 UTC, EdinTC approved these changes

2018-09-01 17:04 UTC, merged